# -*- coding: utf-8 -*-
"""K means.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HGgs2xLF7-p-87Ta64Z4XSolcFkKWk2B
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

X = [[0.1,0.6],[0.15,0.71],[0.08,0.9],[0.16,0.85],[0.2,0.3],[0.25,0.5],[0.24,0.1],[0.3,0.2]]

centers = np.array([[0.1,0.6],[0.3,0.2]])
print ("Initial centroids:",centers)

from sklearn.cluster import KMeans 
model = KMeans(n_clusters=2, init= centers, n_init=1)
model.fit(X)
print("labels:",model.labels_)

print ("P6 Belongs to cluster", model.labels_[5])

print ("No of population around cluster 2:", np.count_nonzero(model.labels_ == 1))

print ('New centroids', model.cluster_centers_)

